### ISSUE TITLE
Alas使用最新版的DroidCast_raw后无法截图

### ISSUE THREAD

**Issue by stormyyd** [Torther/DroidCastS#2]
作者你好，我是Alas的用户，最近发现Alas更新新版的DroidCast_raw后出现了无法截图的情况（LmeSzinc/AzurLaneAutoScript#2881）。

手动按照本仓库的README.md运行了DroidCast_raw服务，并访问模拟器的`http://127.0.0.1:53516/preview`接口，接口返回如下：

![图片](https://github.com/Torther/DroidCast_raw/assets/4938213/9807f821-fa14-4076-8cb8-5620f3058f36)

错误内容为：`:( Failed to generate the screenshot on device / emulator : redroid - redroid_x86_64 - Android OS : 11`

在服务启动的Shell中，报错如下：

```text
java.lang.ClassNotFoundException: android.view.SurfaceControl$DisplayCaptureArgs
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at java.lang.Class.forName(Class.java:379)
        at ink.mol.droidcast_raw.ScreenCaptorUtils.screenshot(Unknown Source:17)
        at ink.mol.droidcast_raw.AnyRequestCallbackPreview.getScreenImageBitmap(Unknown Source:0)
        at ink.mol.droidcast_raw.AnyRequestCallbackPreview.onRequest(SourceFile:138)
        at com.koushikdutta.async.http.server.i.onRequest(Unknown Source:2)
        at com.koushikdutta.async.http.server.e.q(SourceFile:95)
        at com.koushikdutta.async.http.server.k.a(SourceFile:401)
        at d.i.c(SourceFile:373)
        at g.f.e(SourceFile:20)
        at d.c.e(SourceFile:84)
        at d.v.f(SourceFile:13)
        at d.v.a(SourceFile:3)
        at d.q.run(SourceFile:12)
Caused by: java.lang.ClassNotFoundException: android.view.SurfaceControl$DisplayCaptureArgs
        ... 15 more
```

我使用的模拟器为[Redroid](https://github.com/remote-android/redroid-doc)，版本为11（`redroid/redroid:11.0.0-latest`）。

通过对比[原版DroidCast的代码](https://github.com/rayworks/DroidCast/blob/4a367d9fdd5d561057aa0dde39bea71848825b35/app/src/main/java/com/rayworks/droidcast/ScreenCaptorUtils.java#L52)，发现代码差异主要出现在`Create the DisplayCaptureArgs object by DisplayCaptureArgs$Builder.build()`附近。DroidCast_raw进入相关代码块的条件为`sdkInt >= Build.VERSION_CODES.Q`，即Android版本大于等于9（SDK Version >= 28）；而原版进入相关代码块的条件为`sdkInt >= Build.VERSION_CODES.S`，即Android版本大于等于12（SDK Version >= 31）。从日志与报错信息来看，正是此处的差异导致了在我的模拟器上无法截图。

想了解一下此处的修改是出于什么目的？

**Comment by Torther** [comment]
感谢反馈，会尽快修复

**Comment by Torther** [comment]
目前已修正该错误，ALAS相关的Pr已提交(LmeSzinc/AzurLaneAutoScript#3168)，在此期间，你可以前往本项目的Release下载已修复后的文件。
